BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id = btn_clr
        text: 'Clear'
        on_press: app.handle_clear()

    Button:
        TextInput:
            id: input_name
            text: ''

    Button:
        id: output_label
        text: 'Greet'
        on_press: app.handle_greet()

    Label:
        id: text_box
        text: 'Enter your name'
        color: (1, 1, 0, 1)
